// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe8Zv8V_6SFAZIUkpU6AgB8Xva4z7v2nU',
    appId: '1:67188882942:web:03243c4c4938748ce2d4af',
    messagingSenderId: '67188882942',
    projectId: 'faun-alert',
    authDomain: 'faun-alert.firebaseapp.com',
    storageBucket: 'faun-alert.firebasestorage.app',
    measurementId: 'G-ET14SR03L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhn4aLpv3LE8ul68r9lx-v44gewL0pkEo',
    appId: '1:67188882942:android:ebc41b5697ce9752e2d4af',
    messagingSenderId: '67188882942',
    projectId: 'faun-alert',
    storageBucket: 'faun-alert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRF-w_h1DqiPaRm5pF_LhlQR7QNhC53v8',
    appId: '1:67188882942:ios:835a5b5bf83e17cfe2d4af',
    messagingSenderId: '67188882942',
    projectId: 'faun-alert',
    storageBucket: 'faun-alert.firebasestorage.app',
    iosBundleId: 'com.example.faunAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRF-w_h1DqiPaRm5pF_LhlQR7QNhC53v8',
    appId: '1:67188882942:ios:835a5b5bf83e17cfe2d4af',
    messagingSenderId: '67188882942',
    projectId: 'faun-alert',
    storageBucket: 'faun-alert.firebasestorage.app',
    iosBundleId: 'com.example.faunAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe8Zv8V_6SFAZIUkpU6AgB8Xva4z7v2nU',
    appId: '1:67188882942:web:f1da3ce1c2e492a3e2d4af',
    messagingSenderId: '67188882942',
    projectId: 'faun-alert',
    authDomain: 'faun-alert.firebaseapp.com',
    storageBucket: 'faun-alert.firebasestorage.app',
    measurementId: 'G-7VQ197589E',
  );

}